### ISSUE TITLE
Bad IL format on .net core preview 5

### ISSUE THREAD

**Issue by pcartwright81** [DevExpress/netcore3-wpf-outlook-inspired-app#4]
Steps to reproduce. 
Install .net core preview 5
Open in visual studio
Build and run.  

The below StackTrace is given.   
at DevAVDbViewModel_9be364dd_8b2c_4fcb_897a_27ef17db67f5.get_DocumentManagerService()
   at DevExpress.Mvvm.ViewModel.DocumentsViewModel`2.OnLoaded(TModule module)
   at DevExpress.DevAV.ViewModels.DevAVDbViewModel.OnLoaded(DevAVDbModuleDescription module) in C:\Users\%username%\Source\Repos\netcore3-wpf-outlook-inspired-app\src\DevExpress.OutlookInspiredApp.Wpf\ViewModels\DevAVDbViewModel.cs:line 49
   at DevExpress.Mvvm.UI.EventToCommandBase.OnEventCore(Object sender, Object eventArgs)
   at System.Windows.FrameworkElement.RaiseInitialized(EventPrivateKey key, EventArgs e)
   at System.Windows.FrameworkElement.OnInitialized(EventArgs e)
   at System.Windows.FrameworkElement.TryFireInitialized()
   at System.Windows.FrameworkElement.EndInit()
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.InitializationGuard(XamlType xamlType, Object obj, Boolean begin)

**Comment by pavelovcharov** [comment]
This issue is caused by the breaking change introduced in .NET Core Preview 5. We've fixed it in the 19.1.3 version. You can check the updated demo at https://github.com/DevExpress/netcore-wpf-demos

**Comment by pcartwright81** [comment]
It is working with the other solution.   Thank you.  Closing issue.
